lsst/obs_lsst

policy/lsstCamMapper.yaml
=> fix template for bkgd dataset

policy/lsstCamMapper.yaml, python/lsst/obs/lsstCam/lsstCamMapper.py
Ian and Johann have brought lsstCamMapper.yaml and lsstCamMapper.py up to date based on what we had in `obs_lsstSim` and what is currently in `obs_base`.  We need these changes for processing the coadds.
See discussion starting here: https://lsstc.slack.com/archives/CBE964PR8/p1535474274000100
=> DM-15573 bring lsstCamMapper up to date

config/processCcd.py
=> DM-15853: Update config following DM-10302 changes

config/jointcal.py
Reference catalog configs to match your processCcd configs in case you want to run jointcal.py.
=> DM-15606: Add jointcal configs for filterMap and ref cat

config/ts8/ingest.py, python/lsst/obs/lsst/ts8.py
Add raft data to the serial number dictionary
=> tickets/DM-16473 - Add support for BNL ts8 data

python/lsst/obs/lsst/translators/latiss.py
Updates the time to the date we're supposed to be on the mountain.
=> Updated "on mountain" time to 2019-12-08

python/lsst/obs/lsst/assembly.py
Reconstruct the amp/detector using builders to allow for BBox changes.
=> DM-18610: Add fields, limited mutability, and trim/assembly-state tracking to cameraGeom

policy/comCam/comCamMapper.yaml, policy/lsstCamMapper.yaml
Also clean up some spurious calibDates.
=> Remove refCols from mapper policies.

policy/comCam/comCamMapper.yaml, policy/lsstCamMapper.yaml
This reverts commit 7b8605421759c4458cdcb9bdcd5caea07397a034, reversing
changes made to 3a1ca26540ee34009b5b5f5abb0e5cb91984dcac.
=> Revert "Merge pull request #171 from lsst/tickets/DM-23397"

config/findDefects.py, config/latiss/findDefects.py, policy/lsstCamMapper.yaml
Updates so the defect finding task actually works, and is compatible with ingest.
=> Template and config updates for defects

python/lsst/obs/lsst/instrument.py
Timestamps in calibration labels are now using astropy Time class
instead of datetime.
=> DM-15890: Update code for changes in time format

config/makeBrighterFatterKernel.py
Update overscan configurations.
=> DM-23396: Function "overscanCorrection" in "isrFunctions.py" needs refactoring

policy/lsstCamMapper.yaml
Switch to FITS with the new CrosstalkCalib.
=> DM-23983: Cannot apply crosstalk in Gen 3 DECam processing

config/convolvedFluxes.py, config/forcedPhotCoadd.py, config/makeCoaddTempExp.py, config/measureCoaddSources.py
Needed to run command-line pipe tasks directly on DC2 data instead of `coaddDriver.py` or `multibandDriver.py`.
=> config updates for running command line pipe_tasks on DC2 data

policy/cameraHeader.yaml, policy/lsstCam/R00W.yaml, policy/lsstCam/R04W.yaml, policy/lsstCam/R40W.yaml, policy/lsstCam/R44W.yaml, python/lsst/obs/lsst/assembly.py, python/lsst/obs/lsst/lsstCamMapper.py, python/lsst/obs/lsst/script/generateCamera.py
=> DM-26205: Fix obs_lsst to handle corner raft data

policy/lsstCamMapper.yaml
Add linearity metadata template.
=> DM-26545: Add spline linearizer.

config/imsim/calibrate.py, config/imsim/filterMap.py, config/imsim/measureCoaddSources.py, config/imsim/multiBandDriver.py
per filter definitions as of DM-26138.
=> DM-27670: Add filterMap config for imSim processing

config/imsim/transformSourceTable.py, policy/imsim/Source.yaml, policy/imsim/imsimMapper.yaml
and templates for necessary datasets
=> DM-24349: Add Source Table specification

pipelines/imsim/cpBfkSolve.yaml, pipelines/imsim/cpBias.yaml, pipelines/imsim/cpDark.yaml, pipelines/imsim/cpFlat.yaml, pipelines/imsim/cpPtc.yaml
=> DM-27922: Create initial gen3 calibs for DC2

config/makeCoaddTempExp.py, config/makeWarp.py, config/mergeCoaddDetections.py, config/mergeCoaddMeasurements.py, config/mergeDetections.py, config/mergeMeasurements.py, pipelines/DRP.yaml, pipelines/imsim/DRP.yaml
and add config override files for tasks with
changed DefaultNames in Gen3
=> DM-24638: Add DRP pipeline specification

python/lsst/obs/lsst/translators/phosim.py
A small update to phosim translator, to recognize that if 'INSTRUME' is in the header, it's supposed not to use phosim translator (but ComCam or LsstCam instead)
=> Recognize phosim-looking-like-comcam

pipelines/imsim/cpBias.yaml, pipelines/imsim/cpDark.yaml, pipelines/latiss/cpBias.yaml, pipelines/latiss/cpDark.yaml, pipelines/latiss/cpFringe.yaml
Rename task aliases to match cp_pipe.
=> DM-29589: Fix cp_pipe pipelines to avoid dimension conflict #81

pipelines/imsim/cpFlat.yaml, pipelines/latiss/cpFlat.yaml, pipelines/latiss/cpFringe.yaml
Use CalibCombineByFilterTask where appropriate.
=> DM-29699: CalibCombineConnections changes its quantum dimensions at construction

config/imsim/isr.py, pipelines/imsim/DRP.yaml
Update DRP pipeline for imsim.
=> DM-30351: Make sure brighter-fatter correction is working on DC2 data for DP0.2

config/hsm.py
=> DM-31721: Catch LookupError instead of NotFoundError

pipelines/imsim/DRP.yaml, policy/imsim/ForcedSource.yaml
and make ForcedSource specification agnostic to primary key name
=> DM-31765: Add ForcedPhotOnDiaObject transform tasks to step5

python/lsst/obs/lsst/translators/latiss.py, python/lsst/obs/lsst/translators/lsst.py, python/lsst/obs/lsst/translators/lsstCam.py
* REASON applies to all translators.
* PROGRAM applies to LATISS, LSSTCam and ComCam.
=> DM-33215: Add support for PROGRAM and REASON to translators

python/lsst/obs/lsst/cli/cmd/commands.py, python/lsst/obs/lsst/script/ingestPhotodiode.py
=> DM-34105: Take into account move of instrument options from obs_base to pipe_base

pipelines/imsim/DRP.yaml
Delete from subset, but not Pipeline.
=> DM-34478: Remove ConsolidateForcedSourceTable from step5 subset for DP0.2 processing

python/lsst/obs/lsst/translators/ts8.py
This matches a "valid" TS8 filter definition.
=> DM-35524: Change default TS8 filter from NONE to unknown

python/lsst/obs/lsst/_ingestPhotodiode.py
=> DM-37703: Hide unresolved ref warnings for ingest

python/lsst/obs/lsst/_ingestPhotodiode.py
=> DM-38779: Create a resolved DatasetRef for photo diode ingest

python/lsst/obs/lsst/script/rewrite_latiss_optics_file.py, python/lsst/obs/lsst/script/rewrite_latiss_qe_file.py
The transmission files have been generated into `obs_lsst_data`.
=> DM-39649: Add scripts for default LATISS transmission_detector and transmission_optics.

config/imsim/calibrateImage.py
I forgot to push this earlier.
=> DM-40387: Fix typos in calibrateImage imsim config

tests/test_ingest.py
Depends on lsst/daf_butler#899
=> DM-41365: Use Butler.find_dataset API

config/comCamSim/analysisToolsAstrometricCatalogMatch.py, config/comCamSim/analysisToolsAstrometricCatalogMatchVisit.py, config/comCamSim/analysisToolsPhotometricCatalogMatch.py, config/comCamSim/calibrate.py, config/comCamSim/calibrateImage.py, config/comCamSim/compareWarpAssembleCoadd.py, config/comCamSim/gbdesAstrometricFit.py, config/comCamSim/isr.py, config/comCamSim/measureCoaddSources.py, config/comCamSim/refCatObjectAnalysisTask.py, config/comCamSim/refCatObjectPhotometricAnalysisTask.py
- Enable BF corrections
- Update ref cats
- Shrinks sub regions for coaddition
=> DM-43194: Change configs for sim 2

python/lsst/obs/lsst/translators/lsstCam.py
2024 May data should use 12 hour offset rather than Pacific time.
=> DM-44312: LSSTCam stopped taking data in lab in March 2024

config/comCam/isrLSST.py, config/latiss/isrLSST.py
=> DM-47636: Switch CROSSTALK masking to use subtrahend masking

.gitignore, pyproject.toml, python/lsst/obs/lsst/cli/__init__.py, python/lsst/obs/lsst/cli/_get_cli_subcommands.py, python/lsst/obs/lsst/cli/resources.yaml, tests/SConscript, ups/obs_lsst.table
=> DM-42226: Use entry points for subcommand discovery

config/comCam/finalize_characterization.py
See https://rubinobs.atlassian.net/browse/DM-49152 for more details.
=> DM-49152: Enable C++ solver and use input center for PSF model.

config/comCam/gbdesAstrometricFit.py
See thread [here](https://rubin-obs.slack.com/archives/C07TD4VUJ3X/p1742485414070239)
=> DM-49675: Set value for ref epoch for LSSTComCam.

python/lsst/obs/lsst/translators/lsstCam.py, python/lsst/obs/lsst/translators/lsstCamSim.py, tests/test_translator.py
Even if it is on a test stand.
=> Assume that "is on mountain" is always true for LSSTCam from March 2025

python/lsst/obs/lsst/_ingestPhotodiode.py, python/lsst/obs/lsst/cli/cmd/commands.py, python/lsst/obs/lsst/script/ingestPhotodiode.py
The main blockers on this is now how reliable the blocks/scheduler/etc are at generating GROUPID values.  I think this is ready for review, with the intent that we'll run this manually until we know what that reliability is.
=> DM-44113: Test and update electrometer ingest for FITS files as currently written.
