- config/assembleCoadd.py
- config/makeCoaddTempExp.py
Explicitly set config values instead of relying on defaults.
Add notes that we intend to turn these on in the future.
> Change commented-out config to explicit False.

- config/isr.py
- config/lsstCam.py
- config/processCcd.py
- config/runIsr.py
This ticket adds a stand-alone runIsr.py script, as well as ensuring that runIsr.py and processCcd.py read the same ISR configuration files.
> DM-6640: IsrTask is not a valid CmdLineTask

- config/isr.py
- policy/lsstCamMapper.yaml
The lsstCamMapper has been updated to persist thumbnail images of the
overscan subtracted and flattened ISR images.  These thumbnails are
disabled by default in the config/isr.py file to prevent issues with
auxTel registries that do not contain the `raftName` column available
for phosim and imsim data.
> DM-15862: Reduce ISR code duplication between ip_isr, obs_subaru, and obs_decam

- python/lsst/obs/lsst/testHelper.py
- tests/test_auxTel.py
- tests/test_imsim.py
- tests/test_phosim.py
- tests/test_ts8.py
Creating a butler seems to take "forever" and we are doing it every test. This PR creates a butler ever test class. Tests now take 3 minutes rather than 15 minutes on my laptop.
> DM-17095: Speed up tests

- config/imsim/processCcd.py
- config/imsim/singleFrameDriver.py
- config/phosim/processCcd.py
- config/phosim/singleFrameDriver.py
Handles both processCcd and singleFrameDriver
Tested both processCcd and singleFrameDriver using DESC imsim Run1.2i and Run1.2p repos:
`processCcd.py <pathtorepo> --rerun checkConfig --show config=isr.doCrosstalk`
This change should only impact imsim and phosim processing.
> rationalize handling of doCrosstalk for imsim and phosim

- python/lsst/obs/lsst/lsstCamMapper.py
Increase the maximum exposure ID bits to 36
> DM-17535: 32 bits no longer suffice for imsim expId

- config/bias.py
- config/dark.py
- config/flat.py
Change config.load to config.isr.load in bias.py, dark.py, flat.py (in config directory).
> DM-17766: PR 73 broke obs_lsst for calib construction

- config/bias.py
- config/dark.py
- config/flat.py
- config/lsstCamCommon.py
- config/sky.py
#73 wasn't quite correct. It ended up setting the ccdKeys in config.isr rather than the root config. This broke imsim ci_lsst.  With this change I reintroduce a generic lsstCamCommon configuration that defines ccdKeys.
> DM-17903: Ensure that ccdKeys is set

- config/imsim/processCcd.py
- config/processCcd.py
- policy/cameraHeader.yaml
As agreed at this week's DM-DC2 meeting, we want to merge the config changes from the u/jchiang/run2.xi_stars_only_ref_cats branch into master for use as part of the DC2 Run2.1i processing which will use a star-only reference catalog.
Opening the PR, but would like some guidance on what testing is required by the reviewers @RobertLuptonTheGood @timj  I don't think I can start up a Jenkins stack-os-matrix Job - is that something I should request a DM person to do?
@jchiang87 I think I cherry-picked your 2 commits properly, but please take a peek to make sure.
> DM-17875: DESC config updates for DC2 stars only refererence catalog

- python/lsst/obs/lsst/imsim.py
- python/lsst/obs/lsst/phosim.py
- tests/test_imsim.py
- tests/test_phosim.py
As discussed on SLACK: https://lsstc.slack.com/archives/CBE964PR8/p1552065738002400 ccdExposureId_bits has been set to 38 for both imSim and phoSim.  DESC needs this update for the upcoming DC2 Run2.1i processing.
> DM-18551: update ccdExposureId_bits

- config/imsim/processCcd.py
- config/imsim/singleFrameDriver.py
- config/phosim/processCcd.py
- config/phosim/singleFrameDriver.py
As mentioned on Slack https://lsstc.slack.com/archives/C978LTJGN/p1550252025011800 since DM-17917 there is now the option to select "unresolved" sources in reference catalogs for astrometry matching.  DESC DC2 Run2.1i will be using a reference catalog that has stars + galaxies. This PR adds the configs necessary to imSim and phoSim processCcd processing to utilize this feature.
> Updating configs for star+galaxy ref cats

- config/imsim/processCcd.py
- config/imsim/singleFrameDriver.py
- config/phosim/processCcd.py
- config/phosim/singleFrameDriver.py
The field was called "isresolved" previously due to a miscommunication.  This
has been fixed at the same time as updating the config parameter name.
> DM-18643: Rename referenceSelection to referenceSelector and change default field to "resolved"

- policy/ts8/RTM-013.yaml
- policy/ts8/RTM-015.yaml
- policy/ts8/RTM-016.yaml
- policy/ts8/RTM-019.yaml
- policy/ts8/RTM-020.yaml
- policy/ts8/RTM-021.yaml
- policy/ts8/RTM-022.yaml
- policy/ts8/RTM-023.yaml
- policy/ts8/RTM-024.yaml
- policy/ts8/RTM-025.yaml
- policy/ts8/RTM-031.yaml
- policy/ts8/rafts.yaml
- tests/test_ts8.py
There the raft slot definitions that I extracted from the eTraveler.   I tested RTM-023 with some recent TS8 data and it works fine.   We don't have TS8 data for the other rafts yet.
> Added new raft defintions and mappings for TS8 data-taking

- config/focalPlaneBackground.py
- config/ingestCalibs.py
- config/skyCorr.py
- policy/lsstCamMapper.yaml
This PR includes all the identified configuration updates needed to successfully run skyCorrection on DESC Run2.1i data.  We are hoping to get this in for the next upcoming weekly build.
> DM-19270: sky config updates necessary for DESC DC2 processing

- python/lsst/obs/lsst/ingest.py
In some test stand data it appears as a string.
> DM-19752: Cast MONOWL to float

- policy/lsstCamMapper.yaml
Previously, masking and interpolation was done on a by-defect-type
basis: a set of bad pixels were masked and interpolated, then the
process repeated on different bad pixels. However, this ignores the
case where different types of bad pixels may be contiguous, resulting
in interpolated pixels being derived based on previously interpolated
values.
The new dataset needs a template for the data to be saved.
> DM-19382: Add dataset for preinterp ISR exp.

- config/processCcd.py
because order=2 is the new Task default
> DM-18293: Remove FitTanSipWcs order config override

- policy/lsstCamMapper.yaml
As discussed on JIRA, there are some missing templates.  This PR currently addresses `forcedPhotCcd_metadata`
> DM-19985: add template entry for forcedPhotCcd_metadata

- latiss/SConscript
Now that generateCamera is a bit slower to start up, there was a race between ingestDefects and generateCamera creating the latiss.yaml file. This changes adds an explicit dependency between the two.  I don't seem to be able to declare that `latiss` target depends on `policy` target.
> DM-21187: Ensure that latiss target depends on the latiss camera YAML

- config/imsim/coaddDriver.py
- config/imsim/processCcd.py
- config/isr.py
- policy/lsstCamMapper.yaml
For DC2 Run2.2i, DESC is moving to use DM 18.1.0.  Merging in updates from our dc2/run2.1 branch into the new dc2/run2.2 branch which is based on 18.1.0
> Merge dc2/run2.1 DESC updates into new dc2/run2.2 branch

- policy/lsstCamMapper.yaml
1. Correct `{dcr,deep}Diff_*` visit format strings to explicitly be `%(visit)08d`
2. Add `deepDiff_diaObject`, `deepDiff_forced_diaSrc`, `deepDiff_forced_diaObject`,  `deepDiff_diaObjectId` and accompanying `_schema` dataset types.
3. Adds configs for additional Tasks to support DIA analysis.  
_NOTE_ that these are configs used by `LSSTDESC/dia_pipe`.  While `LSSTDESC/dia_pipe` is not in the main LSST code base, I hope that we can help develop our way toward very similar things being incorporated in LSST repos -- likely eventually in pipe_tasks.
`forcedPhotCcdDiaDriver_config`, `forcedPhotCoaddDiaDriver_config`, `forcedPhotCcdDia_config`, `forcedPhotCoaddDia_config`, `imageDifferenceDriver_config`, `imageDifferenceDriver_metadata`, `associationDriver_config`.
> DM-20524: Add some fixes for DIA analysis

- python/lsst/obs/lsst/gen3/rawFormatter.py
The filters are different for LATISS but the formatter had
not been updated to reflect that.
> DM-22704: Ensure that raw formatter uses correct filter list

- config/imsim/processCcd.py
Also restrict to point sources for reference catalog selection for zp calculation.
> Apply S/N cuts on sources used for aperture correction and zp calculation

- python/lsst/obs/lsst/translators/latiss.py
- tests/test_translator.py
These headers are always wrong since they were calculated
using an incorrect telescope location. Clearing the headers
forces the RA/DEC to be calculated from the RA/DEC demand
headers.
Note that there is a 7 arcmin discrepancy between the demand
header and the position calulated from AZSTART/ELSTART/DATE-OBS.
7 arcmin is a bit higher than I expected.
> DM-23278: Clear RASTART etc headers taken before Feb 2020

- policy/comCam/comCamMapper.yaml
- policy/latiss/latissMapper.yaml
- policy/lsstCamMapper.yaml
`dateObs` is the correct field to test against the validity range.  The formatter information was also incorrect, and there was a leftover unused `defects` policy setting from when these used to be part of the camera object.
> Fix defects policies.

- policy/lsstCamMapper.yaml
refCols is the list of data id keys that may be specified (their
combination must select a unique dateObs). 'visit' is retained for a
future time when 'snap' can also be included.
The reference table was attempting to use a visit optimization, but ISR
will in general act on exposures, not visits, so we change to the 'raw'
table.
> Change calibration refCols and reference table.

- config/convertRepo.py
- config/defineVisits.py
The tests here now just test that trying to define visits from the test data already included in the repo correctly does nothing, because (apparently) none of the exposures here have `observation_type = 'science'`.  When that changes someday in the future (and we include those data IDs in the ingest tests), the tests will fail unless we also set the "visits" attribute to a non-empty dictionary of expected visits, as in the obs_subaru and obs_decam tests.
> DM-15536: adapt to moving visit definition out of ingest

- config/findDefects.py
- config/isr.py
- config/latiss/latiss.py
- config/makeBrighterFatterKernel.py
- config/measurePhotonTransferCurve.py
- config/phosim/measureCrosstalk.py
- config/ts3/ts3.py
- config/ts8/ts8.py
- config/ucd/ucd.py
This PR removes all references to the `IsrConfig.doAddDistortionModel` field, which is no longer  used by `IsrTask`.
> DM-23651: ap_pipe calls some deprecated things

- python/lsst/obs/lsst/__init__.py
- python/lsst/obs/lsst/_instrument.py
- python/lsst/obs/lsst/rawFormatter.py
This allows us to make clear that the internal location
of the LSST gen3 instrument classes is not relevant
to the user of the package.
> DM-25153: Move instrument.py to _instrument.py

- pipelines/latiss/cpBias.yaml
- pipelines/latiss/cpDark.yaml
- pipelines/latiss/cpFlat.yaml
- pipelines/latiss/cpFringe.yaml
> DM-21212: Update existing cp_pipe tasks to pipelineTasks

- python/lsst/obs/lsst/_fitsHeader.py
- python/lsst/obs/lsst/ingest.py
- python/lsst/obs/lsst/lsstCamMapper.py
- python/lsst/obs/lsst/utils.py
- tests/data/LSST-PhoSim-204595.yaml
- tests/test_lsstCam.py
- tests/test_phosim.py
* Add helper function that reads the primary header and merges it with the first amp header. PhoSim requires this.
* Add specialist bypass_raw_hdu so that assembled raws can use the helper function.
* Add specialist bypass_raw_md method that uses the same helper function.  This allows header corrections  to be applied.
* Add new tests to ensure that visitInfo, Exposure, and metadata have header corrections applied.
> DM-25171: Change how headers are read from raw data in gen2

- python/lsst/obs/lsst/utils.py
In a previous development version the function was in that
file but it was moved before merging and the linter did not
spot it but the sphinx build did.
> DM-25461: Remove left over export from __all__

- tests/test_convert2to3.py
> DM-25458: Remove need for specifying calib collection in tests

- pipelines/latiss/cpBias.yaml
- pipelines/latiss/cpDark.yaml
- pipelines/latiss/cpFlat.yaml
- pipelines/latiss/cpFringe.yaml
Fix LATISS pipeline instrument name and inconsistencies.
> DM-25329: Fix LATISS instrument pipeline definitions for cp_pipe

- python/lsst/obs/lsst/_instrument.py
- python/lsst/obs/lsst/lsstCamMapper.py
The cache is moving to yamlCamera.makeCamera.
Tests run 35 seconds faster with yamlCamera caching over
caching separately in gen2 and gen3.
For reference before the cache was added to gen2 mapper
in DM-25890, the tests took 9.5 minutes (no parallelism, on my Mac).
Now they take 5.25 minutes.
Relies on lsst/obs_base#275
> DM-25923: Remove local caching of yaml camera geom in gen2+gen3

- policy/lsstCam/R32.yaml
Just like the QE curves, the gain, read noise, saturation values are bad for run12002 too. For JSR 2020 presentations, we here update the bad read noise values to what is found in Vincent’s Docushare Document-28552. These are the raft acceptance data from BNL.
> update readnoise for R32_S11

- config/datasetIngest-gen3.py
This PR adds a default ImSim configuration for `ap_verify`'s `Gen3DatasetIngestTask`.
> DM-26070: Add visit definition to ap_verify

- pipelines/latiss/cpDark.yaml
- pipelines/latiss/cpFlat.yaml
Modify LATISS calibration production pipelines to fix errors.
> DM-23302: Add ci_cpp package to allow calibration product generation to be tested

- python/lsst/obs/lsst/filters.py
> DM-26738: Rename abstract_filter to band

- python/lsst/obs/lsst/_instrument.py
- python/lsst/obs/lsst/filters.py
- python/lsst/obs/lsst/imsim.py
- python/lsst/obs/lsst/phosim.py
- python/lsst/obs/lsst/rawFormatter.py
- python/lsst/obs/lsst/translators/imsim.py
- python/lsst/obs/lsst/translators/phosim.py
- tests/test_butlerCmd.py
- tests/test_convert2to3.py
- tests/test_gen3.py
LsstImSim -> LsstCamImSim
LsstPhoSim -> LsstCamPhoSim
since these are simulations specifically of LSSTCam.
> DM-26978: Rename imSim and PhoSim instrument/translator classes

- policy/lsstCam/R41.yaml
Update R41_S11_C14's readnoise to 25.0, based on BOT data.
This update allows the regular constructDark.py processing to succeed
on this amplifier, as the elevated read noise prevents the cosmic ray
rejection from identifying everything as a cosmic ray.
> DM-27158: constructDark.py fails on LSSTCam with 'Too many CR pixels'

- python/lsst/obs/lsst/translators/comCam.py
- python/lsst/obs/lsst/translators/imsim.py
- python/lsst/obs/lsst/translators/latiss.py
- python/lsst/obs/lsst/translators/lsst.py
- python/lsst/obs/lsst/translators/lsstCam.py
- python/lsst/obs/lsst/translators/lsst_ucdcam.py
- python/lsst/obs/lsst/translators/ts8.py
- tests/test_translator.py
Depends on lsst/astro_metadata_translator#43
> DM-26696: Support new fix_header API

- python/lsst/obs/lsst/__init__.py
- tests/test_gen3.py
This is a bit fragile, as it assumes the Formatter isn't going to care that the data ID doesn't really make sense, and that may change in the future.  See DM-28698 for further discussion.
> DM-28583: Pass dummy data ID when constructing Formatter in tests.

- config/imsim/transformObjectCatalog.py
- policy/imsim/Object.yaml
to transform multiband outputs to the parquet Object Table
> DM-26393: Add Object.yaml specification

- python/lsst/obs/lsst/translators/lsst.py
- python/lsst/obs/lsst/translators/lsst_ucdcam.py
- python/lsst/obs/lsst/translators/ts3.py
- python/lsst/obs/lsst/translators/ts8.py
- tests/test_ucdcam.py
The naming isn't great, but this is the interpretation that daf_butler and other cameras have assumed, and we need obs_lsst to be the same in order for DimensionPacker to behave consistently with astro_metadata_translator until we can unify that log.
This removes the DETECTOR_MAX override for TS3 because it should just inherit the same value from its base class anyway.
> DM-29019: Interpret detector_max as exclusive bound on zero-based detector_nums.

- policy/imsim/imsimMapper.yaml
- policy/latiss/latissMapper.yaml
- policy/lsstCamMapper.yaml
The policy templates were identical for the icExp and icExpBackground datasets
thus a "put" of one would overwrite the other.  Fixed here by updating the
template of the latter.
> DM-29336: Templates are identical for icExp and icExpBackground in obs_lsst

- pipelines/DRP.yaml
DM-22277 converts to gen3 the tasks the convert the `deepCoadd_{meas|ref|forced_src}` catalogs to `objectTable_tracts`.  I don't have any multiband output in a gen3 repo right now, so I'm excluding it from the DRP pipeline here until tested.  @taranu, you can remove this objectTable  exclusion if it works in your 3828 Gen3 DRP check.
> DM-22277: Exclude objectTable subset from DRP pipeline until tested

- pipelines/latiss/cpBfkSolve.yaml
- policy/latiss/latissMapper.yaml
- policy/lsstCamMapper.yaml
Add LATISS pipeline, and fix mapper expectations.
> DM-24704: Make brighter-fatter correction a subclass of lsst.ip.isr.IsrCalib

- policy/imsim/imsimMapper.yaml
Add an updated bfKernel mapper entry for imsim.
> DM-30738: Backport gen3 imSim BF-kernels for gen2

- config/forcedPhotCoadd.py
- config/measureCoaddSources.py
- policy/imsim/Object.yaml
DM-30649 fixed a config option in assembleCoadd that makes it so the BRIGHT_OBJECT mask plane does not exist, while before it was just never being set (because we don't have any bright object masks for non-HSC instruments, and we never will, at least not in this form).
But this broke downstream processing that expected this mask plane to exist.
> DM-30838: Disable configs and columns about bright object mask flags.

- python/lsst/obs/lsst/assembly.py
- python/lsst/obs/lsst/ingest.py
- python/lsst/obs/lsst/latiss.py
- python/lsst/obs/lsst/script/phosimToRafts.py
- python/lsst/obs/lsst/translators/lsstCam.py
The gen2-specific code is still lsst.log.
> DM-31228: Move some code to python logging

- config/characterizeImage.py
- config/forcedPhotCoadd.py
`doPsfPhotometry` must be set to `True` prior to registering the plugin for
aperture corrections.
> DM-31445: Enable GAaP PSF photometry before apCorr

- python/lsst/obs/lsst/assembly.py
The log message itself (and prefix) were being lost.
> DM-31659: Fix warn_once log command

- python/lsst/obs/lsst/rawFormatter.py
- tests/test_ingest.py
Fix transform for single-amp reads.
If the detector has been modified, then any transforms need to be
relative to the new XY offset position that is calculated during that
modification.
> DM-31760: Single amp reads for obs_lsst have the wrong geometry.

- pipelines/imsim/DRP.yaml
- policy/imsim/ForcedSource.yaml
- policy/imsim/Object.yaml
- policy/imsim/Source.yaml
* Added all the columns used by pipe_analysis and analysis_drp to the object table
* Added all the apertures to the aperture fluxes
*  all dataframes have primary keys as index only
* object table columns look like `g_apFlux` instead of `gApFlux`
* All per-patch datasets are consolidated into a per-tract dataset
* names start with lowercase
I promise to squash these before merging
> DM-31825: Implement RFC-807 on DRP parquet table consistency

- config/characterizeImage.py
- config/forcedPhotCoadd.py
- config/gaap.py
- policy/imsim/Object.yaml
This PR is a duplicate of https://github.com/lsst/obs_lsst/pull/352 that @sr525 reviewed.  It required coordination with DM-31825 and here is the copy that was Jenkins'ed with DM-31825
> DM-31912:  Add additional GAaP circular apertures for DP0.2

- policy/imsim/Object.yaml
Backporting the patch that fixes an error in one of the GAaP color columns
> DM-32448-v23: Fix the column name error for gaap3p0Flux

- policy/imsim/Source.yaml
The single frame extendedness column is used for QA.
Therefore, the fluxes from which it is computed
(gaussian and psf) also be used for QA. If a column is
needed for QA then it will also be needed during analysis.
> DM-32666: Add gaussianFlux to Source Table

- python/lsst/obs/lsst/_ingestPhotodiode.py
This allows escapes to be reverted.
> DM-33762: Use ospath not path when getting path to local file from URI

- python/lsst/obs/lsst/_ingestPhotodiode.py
- tests/test_ingest.py
I've added a call to `ingestRaws` to the photodiode test.  As all tests ingest to a unique collection, this should be a safe way to ensure that the needed exposure information exists.
> DM-33766: Photodiode test depends on other tests having run

- python/lsst/obs/lsst/filters.py
This PR removes remaining support for the obsolete `afw.image.Filter`.
> DM-27177: Remove support for lsst.afw.image.Filter

- config/imsim/objectTableTractAnalysis.py
Analyze same list of bands as produced in Object Table
transformObjectTable explodes out the bands listed in the outputBands
config parameter. Therefore a sensible default for objectTableTractAnalysis
is to make plots and metrics for that same list of bands
> DM-35656: add analysis_tools to drp_pipe and run in ci_imsim

- python/lsst/obs/lsst/rawFormatter.py
In current LATISS data (and likely future comcam & LSSTCAM data), the FITS files may contain extra HDUs "REB_COND" and "CONFIG_COND", which describe some sensor state that does not make sense to be included per-amplifier. This change checks if those HDUs are present, and if they are includes them in the metadata.
> DM-36169: merge extra hard-coded named headers in rawFormatter

- config/isr.py
- config/latiss/isr.py
- policy/cameraHeader.yaml
- python/lsst/obs/lsst/assembly.py
* Set size of ITL overscan region to 64 pixels.
* Remove DETSEC log warning that will always trigger due to external value mismatches.
* Set the overscan.fitType default to MEDIAN_PER_ROW.
> DM-34989: Update obs_lsst to fix common problems.

- python/lsst/obs/lsst/script/rewrite_ts8_qe_files.py
- tests/test_rewrite_qe.py
Update transmission_sensor/qe rewrite and test codee.
> DM-36597: Add LATISS filter transmission data

- config/latiss/isr.py
Add keywords to check for LATISS exposure/calib matching.
> DM-36390: calibrations should track sequencer crc

- config/latiss/calibrate.py
Now that the pointing accruacy and stability has improved for AutTel, the bbox padding for reference catalog loading can be greatly reduced. This has the benefit of avoiding many very bad fits where the matcher locked onto sources way outside of the true field for the exposure.
> DM-38005: Update astrometry reference matcher configs for LATISS

- tests/test_ingest.py
> DM-38210: Use butler.get() rather than deprecated getDirect()

- python/lsst/obs/lsst/assembly.py
- python/lsst/obs/lsst/rawFormatter.py
Reading the raw header was slow. This PR seems to make things 3x faster.
* No longer read CONFIG_COND HDU
* No longer read the first amplifier header.
* No longer try to strip WCS headers (which takes a long time because it has to try to create a WCS) if there is no CRPIX key present.
* Change merge scheme to use "overwrite" instead of "first" since overwriting is much faster.
* Specify the translator class when fixing header (this should have been done all along).
> DM-38520: Optimize raw header reading

- config/latiss/associatedSourcesTractAnalysis.py
- config/latiss/transformObjectCatalog.py
This adds the two config files needed to run photometric repeatability focal plane plots.
> DM-39327: added config files for analysis_tools associatedSourcesTractAnalysis

- config/latiss/isr.py
> DM-39505: Enable crosstalk correction for LATISS

- .github/workflows/yamllint.yaml
- pipelines/imsim/DRP.yaml
Pipelines should go in *_pipe packages.
> DM-35579: Remove pipelines forwarding stubs.

- config/latiss/calibrate.py
- config/latiss/characterizeImage.py
- config/latiss/isolatedStarAssociation.py
The default 12 pixel aperture is much too small for the LATISS platescale.
> DM-40301: Update configurations to use large 35 pixel aperture for LATISS calibration.

- python/lsst/obs/lsst/filters.py
Jenkins run -> https://rubin-ci.slac.stanford.edu/job/stack-os-matrix/36/
Note that the PR is organized in 3 separate commits, one for the new filters, one for the new grating, and the third is for the options of the pinhole masks. The pinhole masks (there are two) will only be installed in the grating wheel, but they have configurable options as far as the aperture size and aperture locations. The names were chosen to express all available configurations as it is unknown ahead of time which aperture size/location configuration will be used.
> DM-40426: Add new LATISS filters collimator and cyl_lens, and new gratings holo4_001 and pinhole mask options. 

- config/latiss/makeWarp.py
These config parameters are in units of pixels
and were too small for the latiss_v1
pixel scale of 0.1.
> DM-41199: Increase target FWHM for PSF-matched warps in LATISS

- config/imsim/analysisToolsAstrometricCatalogMatch.py
- config/imsim/analysisToolsAstrometricCatalogMatchVisit.py
- config/imsim/analysisToolsPhotometricCatalogMatch.py
- config/imsim/analysisToolsPhotometricCatalogMatchVisit.py
for analysis tools photometric matching tasks, because no colorterms apply. Pair coded hotfix with Sophie.
> DM-37727-fix: Add imsim specific overrides

- python/lsst/obs/lsst/script/rewrite_lsstcam_qe_files_DM-40164.py
This script reads in the parquet file provided by @aaronroodman and does some raft-by-raft adjustments and outputs the final curated ecsv curves in {{obs_lsst_data}}.  It also outputs an updated parquet file.
> DM-40164: Add script to update baseline QE curves for lsstCam in obs_lsst_data

- config/latiss/measureCoaddSources.py
On this PR I also added in the correct override of the filter map to allow matches to be turned on if we need them (though I don't think they're actually used anywhere).
> DM-42154: Add config overrides for LATISS multiband to turn off refcat matching.

- python/lsst/obs/lsst/_ingestPhotodiode.py
- python/lsst/obs/lsst/_packer.py
- python/lsst/obs/lsst/assembly.py
- python/lsst/obs/lsst/cameraTransforms.py
- python/lsst/obs/lsst/utils.py
- tests/test_packer.py
This reverts commit 3b1bd75aeaf784dc57c1eb60f8ba222b796f5934 which was working around a bug which has now been fixed in lsst/daf_butler#969.
> DM-43117: Now use exposure.day_obs in query again.

- config/comCamSim/isr.py
100% my fault for not checking together earlier. The default is False and so the the doBrighterFatter=False that was there earlier was doing nothing.
> DM-43194-fix: Add doBrighterFatter override to isr

- config/comCamSim/analysisToolsPhotometricCatalogMatchVisit.py
- config/comCamSim/refCatSourceAnalysisTask.py
- config/comCamSim/refCatSourcePhotometricAnalysisTask.py
The  RefCatSourcePhotometricAnalysisTask one, as of now is necessary, but not sufficient.
> DM-43347: Configure visit-level refcat match analysis tools  tasks for ComCamSim 

- config/comCamSim/calibrate.py
- config/comCamSim/calibrateImage.py
- config/comCamSim/computeExposureSummaryStats.py
- config/comCamSim/updateVisitSummary.py
Adds fiducial values of seeing, sky brightness, and zeropoints for comCamSim in preparation for processing of Ops Rehearsal 3. Note: fiducials are not set for the `characterizeImage` task, since there is no comCamSim-specific config for this task.
> DM-42747: Fiducial values for summary stats for comCamSim

- config/comCamSim/calibrateImage.py
This PR fixes an incorrectly named variable in the CalibrateImage config.
> DM-43576: ComCamSim config overrides for CalibrateImage cannot be applied

- policy/comCamSim/cameraTransforms.yaml
This reverts commit b3a6a4fe347c18dd9c413dd251d92e046fd3f72f from DM-43674.
> DM-44691: Revert "Switch comCamSim to use the LSSTCam distortion model"

- config/latiss/fgcmFitCycle.py
This can be reverted to the full filter list with DM-44705 which will redefine the plot connections.
> DM-44666: Update fgcmFitCycle LATISS physicalFilterMap with limited list of input filters.

- config/comCamSim/computeExposureSummaryStats.py
Update comCamSim fiducial values to come from the system engineering throughputs collected in [SMTN-002](https://smtn-002.lsst.io/) and in [Syseng Throughputs Repo Demo.ipynb](https://github.com/lsst-pst/syseng_throughputs/blob/main/notebooks/Syseng%20Throughputs%20Repo%20Demo.ipynb).
> DM-44855: Update effectiveTime fiducial values for comCamSim

- config/comCamSim/fgcmBuildFromIsolatedStars.py
- config/latiss/calibrate.py
- config/latiss/characterizeImage.py
- config/latiss/fgcmBuildFromIsolatedStars.py
- config/latiss/isolatedStarAssociation.py
Additionally, this adds some missing astrometry-related fields from the isolated star catalog for LATISS.
> DM-38632: Update LATISS and ComCamSim configurations for compensated tophat calibration fluxes.

- config/comCamSim/makeWarp.py
In looking at the template generation run for OpsRehearsal4 (see DM-44718), the thresholds for inclusion in the coadds can be relaxed for the medianE and psfTraceRadiusDelta metrics.
> DM-44928: Relax PSF quality metrics thresholds for inclusion in coadd for LSSTComCamSim

- config/latiss/calibrateImage.py
Prior to this fix the psf code was normalizing to 12 pixel aperture fluxes which only accidentally worked.  When I fixed the aperture radii to use the preferred LATISS 35 pixels that turned out to break the psf fitting.
> DM-44908-hotfix: Fix CalibrateImage LATISS psf fitting overrides to be fully consistent.

- python/lsst/obs/lsst/script/write_comcam_estimated_transmission_sensor.py
- python/lsst/obs/lsst/script/write_comcam_filter_files.py
- python/lsst/obs/lsst/script/write_comcam_optics_file.py
These are scripts to (a) average the ITL sensor QE curves; (b) make filter and optics transmission curves based on the official throughputs v1.9.
> DM-45391: Add scripts to make baseline ComCam curated calibrations. 

- python/lsst/obs/lsst/translators/comCamSim.py
Rather than trying to calculate a junk value from inconsistent headers using a calculation that was in fact broken.
> DM-46177: Force AZEL for ComCamSim to default to 0, 45 if missing

- config/comCam/fiducialSkyBackground.py
- config/comCam/fiducialZeroPoint.py
- config/comCamSim/fiducialSkyBackground.py
- config/comCamSim/fiducialZeroPoint.py
- config/lsstCam/fiducialSkyBackground.py
- config/lsstCam/fiducialZeroPoint.py
ComCam, ComCamSim and lsstCam will produce images in units of electrons. This means that the sky background and zeropoint values should be updated to be in units of electrons. This is actually the native unit of SMTN-002, so in many ways this is cleaner than what was being done before (which involved estimating and applying the gain).
> DM-47034: Convert effTime fiducials to electrons

- config/comCam/analysisToolsPhotometricCatalogMatch.py
- config/comCam/analysisToolsPhotometricCatalogMatchVisit.py
- config/comCam/calibrateImage.py
- config/comCam/filterMap.py
- config/comCam/measureCoaddSources.py
- config/latiss/refCatObjectPhotometricAnalysisTask.py
Here we update the configuration for comcam to use the_monster as a refcat
> DM-46918 update config/ComCam to use the_monster as a refcat

- config/comCam/isrLSST.py
We have usable flats for r and i now, so turn them on.
We also have some uncertainty for the gains, so turn on the amp offset code.
> DM-47197: Turn on flat fielding and amp offsets for LSSTComCam.

- config/comCam/fgcmBuildFromIsolatedStars.py
- config/comCam/fgcmFitCycle.py
- config/comCam/fgcmMakeLut.py
- config/comCam/fgcmOutputProducts.py
> DM-47303: Add fgcmcal configurations for LSSTComCam

- config/comCam/finalize_characterization.py
Based on first iteration if ComCam I can see that increasing spatial interpolation of PSF parameters from order 2 to order 3 it removes most of spatial structures in second moment of PSF second moment residuals.
> Increase spacial order interpolation for PSF/Piff

- config/comCam/finalize_characterization.py
We now have the option to set a per-band config for the spatial order of the final PSF modle fit.  This sets our preferred overrides for LSSTComCam, which are motivated by the fact that u band will almost always have fewer PSF canditates than the other bands (throughput, stellar SED, etc.), and that u-band coadds are highly unlikely to be used in lensing/shear analyses. Setting a smaller spatial order for u precludes an attempt at a higher order fit that inevitably won't be well-constrained (and currently piff does not handle this internally and returns a dodgy PSF model).
> DM-49673-v29: Add per-band spatialOrder config option in piff and add a minNPsfStar criterion for detector rejection

- python/lsst/obs/lsst/_packer.py
- python/lsst/obs/lsst/translators/lsst.py
- tests/test_packer.py
Old behavior can be recovered by calling use_controllers() on the config object, which is what some of the tests do and how the compute_detector_exposure_id implementation on the translator now works.
> DM-49997: Drop controller from dimension packing by default.

- python/lsst/obs/lsst/translators/lsst.py
- python/lsst/obs/lsst/translators/ts3.py
- tests/test_gen3.py
Rather than derive from controller code we have to lock it into place to prevent churn in the dimension record definition.
> DM-50063: Fix the max_exposure_id value to be historical value

- python/lsst/obs/lsst/translators/lsst.py
- python/lsst/obs/lsst/translators/ts3.py
- tests/test_gen3.py
Rather than derive from controller code we have to lock it into place to prevent churn in the dimension record definition.
> DM-50063 (v29): Fix the max_exposure_id value to be historical value

- python/lsst/obs/lsst/translators/lsstCam.py
The code assumed that no TSTAND meant that the instrument was on sky, but we ended up taking on-telescope data with TSTAND = TMAMCv1_SUM so we have to look for strings like that.
> DM-50076: Allow LSSTCam on sky to be indicated by special TSTAND value

- python/lsst/obs/lsst/script/rewrite_latiss_optics_file.py
- python/lsst/obs/lsst/script/rewrite_latiss_qe_file.py
- python/lsst/obs/lsst/script/rewrite_lsstcam_qe_files_DM-40164.py
- python/lsst/obs/lsst/script/rewrite_lsstcam_qe_files_DM-49283.py
- python/lsst/obs/lsst/script/rewrite_ts8_qe_files.py
- python/lsst/obs/lsst/script/write_comCamSim_filter_files.py
- python/lsst/obs/lsst/script/write_comCamSim_optics_file.py
- python/lsst/obs/lsst/script/write_comcam_estimated_non_linear_crosstalk_coeffs.py
- python/lsst/obs/lsst/script/write_comcam_estimated_transmission_sensor.py
- python/lsst/obs/lsst/script/write_comcam_filter_files.py
- python/lsst/obs/lsst/script/write_comcam_manual_defects.py
- python/lsst/obs/lsst/script/write_comcam_optics_file.py
- python/lsst/obs/lsst/script/write_latiss_crosstalk_coeffs.py
- python/lsst/obs/lsst/script/write_lsstcam_manual_defects.py
- python/lsst/obs/lsst/script/write_lsstcam_transmission_filter_detector.py
- python/lsst/obs/lsst/script/write_lsstcam_transmission_optics.py
- python/lsst/obs/lsst/script/write_non_linear_crosstalk_coeffs.py
- python/lsst/obs/lsst/utils.py
We are always using ISO format strings so there is no benefit to using dateutil's advanced heuristics for the date parsing.
Requires lsst/obs_base#515
> DM-49900: Replace dateutil.parser with astropy Time

- config/comCamSim/isrLSST.py
This PR turns off ISR's minimum voltage check for `ComCamSim`, where it's not applicable.
> DM-50625: ComCamSim can't pass minimum voltage check

- python/lsst/obs/lsst/translators/lsstCam.py
Allow tuple sequence ranges for a single day
> DM-51847: Allow sequence ranges for a single day in fix-header
